### ISSUE TITLE
download HC-STVG v1 with 5660 videos

### ISSUE THREAD

**Issue by LIUQI-creat** [tzhhhh123/HC-STVG#16]
Hi，
I'd like to download HC-STVG v1 with 5660 videos, but I found that only the version 2.0 (10 zip files) is provided in the link. It is too large for me. Could you please give the new link that only has HC-STVG v1 with 5660 videos?
Thank you very much.

**Comment by tzhhhh123** [comment]
We have updated the v1 version.
