### ISSUE TITLE
Update data download link.

### ISSUE THREAD

**Issue by Midkey** [tzhhhh123/HC-STVG#21]
Thanks for your excellent work! The Download link of Baidu Yun is not work. Could you please update a new one?

**Comment by a213402010** [comment]
Have you solved this problem, or have you successfully downloaded the data set? Can you send me a copy on Baidu Cloud

**Comment by kelly-accept** [comment]
Have you solved this problem, or have you successfully downloaded the data set? Can you send me a copy on Baidu Cloud，Please reply to me when you see the trouble, thank you very much

**Comment by Midkey** [comment]
You can download the dataset directly with the One Drive.
